### ISSUE TITLE
Quick usability question

### ISSUE THREAD

**Issue by bilsou** [mtojo/j2n#1]
Been playing with your JNI generator and your example with `androidsdk-21`. I looked at the code produced, looked really decent to me.
As I didn't see any example and how usable the generated code was, my only question would be if you ever used for personal projects and what did you learn from it ?

**Comment by mtojo** [comment]
I confirmed this tool actually works. But when used for the Android SDK, compiling time took too much time. So I didn't used it in any project.

**Comment by bilsou** [comment]
So you used it with a smaller JAR you mean ?
I can imagine it might slow compiling the whole generated android SDK, it's a lot of files.

**Comment by mtojo** [comment]
No, I am not using anything. I was planning to use with the Android SDK, but I gave up for the reasons above.

**Comment by bilsou** [comment]
Fair enough, will try to play with it a bit longer, thank you for your answers.
